In [1]:
import pandas as pd
df=pd.read_csv('orders_practice.csv')
df.columns

Index(['Order ID', 'Customer Name', 'Gender', 'Age', 'City', 'Order Date',
       'Product', 'Qty', 'Unit Price', 'Total Amount', 'Payment Mode',
       'Rating'],
      dtype='str')

In [2]:
Missing_age=df['Age'].isna()
display(df[Missing_age])
display(len(df[Missing_age]))

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
11,SP100011,Pooja Singh,Female,NaN,Mumbai,2025-02-21,Headphones,4,2500,10000,UPI,1.0
25,SP100025,Sneha Nair,Female,NaN,Chennai,2025-02-07,Phone,3,22000,66000,UPI,4.0
30,SP100030,Aarav Gupta,Female,NaN,Pune,2025-07-22,Headphones,5,2500,12500,Card,1.0
76,SP100076,Yash Iyer,Male,NaN,Bengaluru,2025-06-24,Phone,3,22000,66000,UPI,3.0
85,SP100085,Kavya Mehta,Male,NaN,Pune,2025-01-21,Charger,5,900,4500,Cash,4.5
126,SP100126,Arjun Gupta,Male,NaN,Mumbai,2025-05-17,Headphones,5,2500,12500,Net Banking,NaN
155,SP100155,Rahul Joshi,Male,NaN,Nashik,2025-10-10,Headphones,5,2500,12500,Net Banking,4.5
156,SP100156,Vikram Iyer,Female,NaN,Nashik,2025-08-09,Headphones,2,2500,5000,Net Banking,5.0
167,SP100167,Anjali Kulkarni,Female,NaN,Mumbai,2025-06-03,Webcam,3,2200,6600,Net Banking,3.5

9

In [9]:
Missing_Rating_City=(df['Rating'].isna())|(df['City'].isna())
df[Missing_Rating_City]

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
14,SP100014,Anjali Singh,Female,58.0,Mumbai,2025-03-27,Charger,2,900,1800,Net Banking,NaN
54,SP100054,Sneha Patil,Female,18.0,NaN,2025-08-04,Monitor,1,9000,9000,Cash,4.0
57,SP100057,Anjali Shah,Male,34.0,Nashik,2025-07-11,Charger,3,900,2700,Net Banking,NaN
68,SP100068,Kavya Iyer,Male,56.0,Delhi,2025-08-05,Monitor,1,9000,9000,Card,NaN
87,SP100087,Rohan Patil,Female,41.0,Bengaluru,2025-09-29,Keyboard,2,1200,2400,Cash,NaN
90,SP100090,Vikram Gupta,Male,51.0,NaN,2025-03-05,Laptop,1,55000,55000,Card,1.0
92,SP100092,Arjun Patil,Male,63.0,Bengaluru,2025-04-20,Webcam,3,2200,6600,Card,NaN
104,SP100104,Arjun Nair,Female,23.0,Pune,2025-08-08,Monitor,5,9000,45000,Cash,NaN
106,SP100106,Rohan Kulkarni,Female,35.0,NaN,2025-08-22,Webcam,4,2200,8800,Card,1.0
111,SP100111,Sneha Mehta,Male,40.0,Nashik,2025-08-03,Monitor,2,9000,18000,Cash,NaN
115,SP100115,Arjun Iyer,Male,45.0,Mumbai,2025-11-07,Headphones,3,2500,7500,Card,NaN
120,SP100120,Kavya Kulkarni,Female,61.0,Bengaluru,2025-09-21,Charger,3,900,2700,Card,NaN
126,SP100126,Arjun Gupta,Male,NaN,Mumbai,2025-05-17,Headphones,5,2500,12500,Net Banking,NaN
145,SP100145,Priya Mehta,Female,19.0,NaN,2025-06-16,Headphones,1,2500,2500,Card,3.5
146,SP100146,Aarav Shah,Female,21.0,NaN,2025-05-21,Webcam,2,2200,4400,Net Banking,1.0
187,SP100187,Karan Iyer,Male,22.0,Pune,2025-11-24,Laptop,2,55000,110000,Cash,NaN
191,SP100191,Aarav Kulkarni,Male,41.0,Pune,2025-06-29,Laptop,5,55000,275000,Card,NaN
196,SP100196,Rohan Gupta,Female,53.0,NaN,2025-06-21,Webcam,5,2200,11000,Net Banking,2.0

In [21]:
wrong_age = (df['Age'] < 18) | (df['Age'] > 100)
df[wrong_age]

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
7,SP100007,Neha Patil,Female,150.0,Pune,2025-03-24,Webcam,1,2200,2200,Cash,4.0
84,SP100084,Yash Shah,Male,16.0,Mumbai,2025-01-19,Headphones,4,2500,10000,Net Banking,4.0
88,SP100088,Arjun Patil,Female,-5.0,Mumbai,2025-03-12,Laptop,5,55000,275000,UPI,2.0
136,SP100136,Meera Mehta,Female,16.0,Pune,2025-06-15,Laptop,1,55000,55000,Net Banking,4.0
144,SP100144,Yash Singh,Male,17.0,Nashik,2025-12-17,Webcam,3,2200,6600,Cash,1.0
153,SP100153,Yash Patil,Female,17.0,Mumbai,2025-02-10,Laptop,1,55000,55000,Cash,4.0
199,SP100199,Anjali Joshi,Female,16.0,Bengaluru,2025-12-29,Mouse,3,600,1800,Card,2.0

In [24]:
Not_Rating_age=(df['Rating'].notna())&(df['Age'].notna())
df[Not_Rating_age]

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
0,SP100000,Isha Singh,Male,58.0,Mumbai,2025-09-12,Laptop,4,55000,220000,UPI,1.0
1,SP100001,Dev Kulkarni,Female,55.0,Bengaluru,2025-02-16,Mouse,5,600,3000,Net Banking,3.5
2,SP100002,Sneha Iyer,Female,48.0,Delhi,2025-10-28,Mouse,2,600,1200,Cash,3.5
3,SP100003,Priya Verma,Female,19.0,Nashik,2025-10-30,Keyboard,2,1200,2400,Card,4.0
4,SP100004,Dev Nair,Male,64.0,Delhi,2025-11-22,Phone,4,22000,88000,Cash,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...
195,SP100195,Priya Singh,Female,36.0,Bengaluru,2025-07-14,Charger,4,900,3600,Cash,2.0
196,SP100196,Rohan Gupta,Female,53.0,NaN,2025-06-21,Webcam,5,2200,11000,Net Banking,2.0
197,SP100197,Isha Nair,Female,18.0,Nashik,2025-05-05,Webcam,5,2200,11000,UPI,4.5
198,SP100198,Priya Kulkarni,Female,55.0,Chennai,2025-03-19,Monitor,4,9000,36000,UPI,5.0
199,SP100199,Anjali Joshi,Female,16.0,Bengaluru,2025-12-29,Mouse,3,600,1800,Card,2.0

In [35]:
good_order=(df['Total Amount']>10000) & (df['Rating']>=4) & (df['City'].notna())
display(df[good_order])
print(good_order.sum())

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
4,SP100004,Dev Nair,Male,64.0,Delhi,2025-11-22,Phone,4,22000,88000,Cash,4.5
19,SP100019,Karan Nair,Female,20.0,Delhi,2025-02-13,Monitor,4,9000,36000,Card,5.0
20,SP100020,Neha Joshi,Male,29.0,Chennai,2025-12-20,Headphones,5,2500,12500,Card,4.5
25,SP100025,Sneha Nair,Female,NaN,Chennai,2025-02-07,Phone,3,22000,66000,UPI,4.0
31,SP100031,Rohan Mehta,Male,48.0,Chennai,2025-09-23,Monitor,4,9000,36000,Net Banking,4.5
36,SP100036,Vikram Gupta,Male,41.0,Delhi,2025-04-26,Webcam,5,2200,11000,UPI,4.5
48,SP100048,Anjali Kulkarni,Male,27.0,Delhi,2025-07-13,Headphones,5,2500,12500,Net Banking,4.0
58,SP100058,Rohan Shah,Male,62.0,Chennai,2025-02-06,Laptop,5,55000,275000,Net Banking,4.5
59,SP100059,Vikram Iyer,Male,56.0,Bengaluru,2025-10-12,Webcam,5,2200,11000,Cash,4.0
63,SP100063,Arjun Nair,Male,50.0,Pune,2025-04-19,Monitor,2,9000,18000,Net Banking,5.0
64,SP100064,Tanvi Singh,Female,32.0,Delhi,2025-07-15,Monitor,5,9000,45000,Net Banking,4.5
71,SP100071,Dev Kulkarni,Female,55.0,Bengaluru,2025-06-29,Monitor,3,9000,27000,UPI,4.0
72,SP100072,Sahil Patil,Female,21.0,Chennai,2025-02-02,Phone,5,22000,110000,Card,4.0
73,SP100073,Yash Kulkarni,Male,49.0,Chennai,2025-05-02,Monitor,3,9000,27000,Cash,5.0
77,SP100077,Aarav Kulkarni,Female,63.0,Delhi,2025-02-13,Monitor,5,9000,45000,Card,4.5
80,SP100080,Rahul Iyer,Female,55.0,Bengaluru,2025-02-10,Laptop,2,55000,110000,Card,5.0
81,SP100081,Isha Mehta,Female,57.0,Mumbai,2025-02-08,Laptop,5,55000,275000,Cash,5.0
83,SP100083,Neha Patil,Female,54.0,Chennai,2025-03-14,Phone,2,22000,44000,UPI,5.0
89,SP100089,Rahul Iyer,Female,46.0,Bengaluru,2025-01-20,Laptop,4,55000,220000,UPI,4.0
107,SP100107,Riya Verma,Male,24.0,Chennai,2025-03-02,Monitor,2,9000,18000,Card,4.5
112,SP100112,Anjali Mehta,Female,58.0,Nashik,2025-08-21,Laptop,1,55000,55000,Cash,4.0
125,SP100125,Priya Kulkarni,Female,20.0,Pune,2025-07-22,Phone,3,22000,66000,Cash,4.5
128,SP100128,Meera Gupta,Male,18.0,Nashik,2025-03-27,Monitor,4,9000,36000,UPI,4.0
136,SP100136,Meera Mehta,Female,16.0,Pune,2025-06-15,Laptop,1,55000,55000,Net Banking,4.0
153,SP100153,Yash Patil,Female,17.0,Mumbai,2025-02-10,Laptop,1,55000,55000,Cash,4.0
155,SP100155,Rahul Joshi,Male,NaN,Nashik,2025-10-10,Headphones,5,2500,12500,Net Banking,4.5
157,SP100157,Dev Gupta,Male,31.0,Bengaluru,2025-10-19,Laptop,2,55000,110000,UPI,4.0
159,SP100159,Meera Shah,Female,24.0,Bengaluru,2025-09-22,Monitor,2,9000,18000,Net Banking,4.0
169,SP100169,Isha Nair,Male,50.0,Delhi,2025-02-24,Webcam,5,2200,11000,Card,5.0
178,SP100178,Aarav Iyer,Female,28.0,Pune,2025-02-06,Laptop,2,55000,110000,Card,4.5
180,SP100180,Neha Mehta,Male,18.0,Mumbai,2025-06-25,Laptop,3,55000,165000,UPI,5.0
185,SP100185,Neha Patil,Male,58.0,Delhi,2025-08-02,Laptop,2,55000,110000,Cash,4.5
186,SP100186,Sahil Nair,Female,36.0,Mumbai,2025-10-05,Monitor,2,9000,18000,UPI,4.5
197,SP100197,Isha Nair,Female,18.0,Nashik,2025-05-05,Webcam,5,2200,11000,UPI,4.5
198,SP100198,Priya Kulkarni,Female,55.0,Chennai,2025-03-19,Monitor,4,9000,36000,UPI,5.0

35