In [1]:
import pandas as pd
df=pd.read_csv('orders_practice.csv')

In [4]:
df.iloc[0:20,0:3]

    Order ID  Customer Name  Gender
0   SP100000     Isha Singh    Male
1   SP100001   Dev Kulkarni  Female
2   SP100002     Sneha Iyer  Female
3   SP100003    Priya Verma  Female
4   SP100004       Dev Nair    Male
5   SP100005    Meera Singh    Male
6   SP100006     Meera Iyer    Male
7   SP100007     Neha Patil  Female
8   SP100008    Sneha Gupta  Female
9   SP100009     Sahil Nair  Female
10  SP100010     Sahil Shah  Female
11  SP100011    Pooja Singh  Female
12  SP100012     Isha Singh  Female
13  SP100013    Priya Verma  Female
14  SP100014   Anjali Singh  Female
15  SP100015     Yash Mehta    Male
16  SP100016    Arjun Singh    Male
17  SP100017  Riya Kulkarni  Female
18  SP100018     Neha Joshi    Male
19  SP100019     Karan Nair  Female

In [5]:
df.loc[10:19,['Customer Name','Rating']]

    Customer Name  Rating
10     Sahil Shah     4.0
11    Pooja Singh     1.0
12     Isha Singh     4.0
13    Priya Verma     3.5
14   Anjali Singh     NaN
15     Yash Mehta     4.5
16    Arjun Singh     1.0
17  Riya Kulkarni     3.5
18     Neha Joshi     3.0
19     Karan Nair     5.0

In [6]:
df.columns

Index(['Order ID', 'Customer Name', 'Gender', 'Age', 'City', 'Order Date',
       'Product', 'Qty', 'Unit Price', 'Total Amount', 'Payment Mode',
       'Rating'],
      dtype='str')

In [10]:
df.iloc[-10:,:]

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
190,SP100190,Dev Mehta,Male,28.0,Pune,2025-02-28,Mouse,3,600,1800,UPI,5.0
191,SP100191,Aarav Kulkarni,Male,41.0,Pune,2025-06-29,Laptop,5,55000,275000,Card,NaN
192,SP100192,Sahil Singh,Male,22.0,Delhi,2025-02-15,Keyboard,3,1200,3600,UPI,5.0
193,SP100193,Sahil Iyer,Male,24.0,Delhi,2025-07-22,Laptop,3,55000,165000,Net Banking,2.0
194,SP100194,Tanvi Shah,Male,21.0,Mumbai,2025-12-01,Phone,2,22000,44000,UPI,3.0
195,SP100195,Priya Singh,Female,36.0,Bengaluru,2025-07-14,Charger,4,900,3600,Cash,2.0
196,SP100196,Rohan Gupta,Female,53.0,NaN,2025-06-21,Webcam,5,2200,11000,Net Banking,2.0
197,SP100197,Isha Nair,Female,18.0,Nashik,2025-05-05,Webcam,5,2200,11000,UPI,4.5
198,SP100198,Priya Kulkarni,Female,55.0,Chennai,2025-03-19,Monitor,4,9000,36000,UPI,5.0
199,SP100199,Anjali Joshi,Female,16.0,Bengaluru,2025-12-29,Mouse,3,600,1800,Card,2.0

In [11]:
df.iloc[::5,:]

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
0,SP100000,Isha Singh,Male,58.0,Mumbai,2025-09-12,Laptop,4,55000,220000,UPI,1.0
5,SP100005,Meera Singh,Male,18.0,Bengaluru,2025-02-26,Webcam,1,2200,2200,Cash,4.0
10,SP100010,Sahil Shah,Female,55.0,Chennai,2025-08-31,Webcam,1,2200,2200,Card,4.0
15,SP100015,Yash Mehta,Male,49.0,Mumbai,2025-07-23,Webcam,2,2200,4400,Cash,4.5
20,SP100020,Neha Joshi,Male,29.0,Chennai,2025-12-20,Headphones,5,2500,12500,Card,4.5
25,SP100025,Sneha Nair,Female,NaN,Chennai,2025-02-07,Phone,3,22000,66000,UPI,4.0
30,SP100030,Aarav Gupta,Female,NaN,Pune,2025-07-22,Headphones,5,2500,12500,Card,1.0
35,SP100035,Anjali Singh,Female,65.0,Mumbai,2025-11-22,Mouse,1,600,600,UPI,4.5
40,SP100040,Kabir Iyer,Male,41.0,Delhi,2025-02-22,Charger,4,900,3600,Net Banking,1.0
45,SP100045,Neha Shah,Female,43.0,Mumbai,2025-08-20,Charger,5,900,4500,Net Banking,1.0
50,SP100050,Kavya Gupta,Male,38.0,Bengaluru,2025-04-01,Laptop,4,55000,220000,Card,2.0
55,SP100055,Sahil Nair,Female,41.0,Chennai,2025-11-16,Webcam,2,2200,4400,Net Banking,4.5
60,SP100060,Dev Patil,Female,42.0,Pune,2025-07-07,Mouse,4,600,2400,Net Banking,5.0
65,SP100065,Vikram Gupta,Female,42.0,Chennai,2025-08-20,Keyboard,4,1200,4800,UPI,3.0
70,SP100070,Sneha Patil,Male,44.0,Mumbai,2025-07-28,Mouse,4,600,2400,Card,3.5
75,SP100075,Priya Iyer,Female,37.0,Chennai,2025-05-20,Charger,1,900,900,UPI,4.5
80,SP100080,Rahul Iyer,Female,55.0,Bengaluru,2025-02-10,Laptop,2,55000,110000,Card,5.0
85,SP100085,Kavya Mehta,Male,NaN,Pune,2025-01-21,Charger,5,900,4500,Cash,4.5
90,SP100090,Vikram Gupta,Male,51.0,NaN,2025-03-05,Laptop,1,55000,55000,Card,1.0
95,SP100095,Karan Singh,Female,46.0,Delhi,2025-08-20,Laptop,2,55000,110000,Net Banking,3.0
100,SP100100,Pooja Gupta,Male,62.0,Nashik,2025-07-03,Webcam,4,2200,8800,Cash,3.5
105,SP100105,Rahul Iyer,Male,65.0,Delhi,2025-10-09,Mouse,2,600,1200,Card,3.0
110,SP100110,Yash Patil,Male,25.0,Pune,2025-11-28,Keyboard,3,1200,3600,Net Banking,1.0
115,SP100115,Arjun Iyer,Male,45.0,Mumbai,2025-11-07,Headphones,3,2500,7500,Card,NaN
120,SP100120,Kavya Kulkarni,Female,61.0,Bengaluru,2025-09-21,Charger,3,900,2700,Card,NaN
125,SP100125,Priya Kulkarni,Female,20.0,Pune,2025-07-22,Phone,3,22000,66000,Cash,4.5
130,SP100130,Isha Gupta,Female,49.0,Pune,2025-03-28,Webcam,3,2200,6600,Card,4.5
135,SP100135,Neha Iyer,Male,40.0,Delhi,2025-02-19,Laptop,2,55000,110000,UPI,3.0
140,SP100140,Anjali Nair,Male,23.0,Delhi,2025-11-16,Webcam,2,2200,4400,UPI,2.0
145,SP100145,Priya Mehta,Female,19.0,NaN,2025-06-16,Headphones,1,2500,2500,Card,3.5
150,SP100150,Vikram Nair,Female,28.0,Nashik,2025-06-25,Mouse,2,600,1200,Net Banking,4.0
155,SP100155,Rahul Joshi,Male,NaN,Nashik,2025-10-10,Headphones,5,2500,12500,Net Banking,4.5
160,SP100160,Sahil Nair,Male,60.0,Mumbai,2025-08-05,Headphones,4,2500,10000,UPI,1.0
165,SP100165,Priya Verma,Male,27.0,Nashik,2025-11-15,Phone,1,22000,22000,Net Banking,2.0
170,SP100170,Isha Patil,Female,58.0,Nashik,2025-11-30,Headphones,1,2500,2500,UPI,2.0
175,SP100175,Karan Nair,Female,31.0,Delhi,2025-08-11,Charger,5,900,4500,Cash,4.0
180,SP100180,Neha Mehta,Male,18.0,Mumbai,2025-06-25,Laptop,3,55000,165000,UPI,5.0
185,SP100185,Neha Patil,Male,58.0,Delhi,2025-08-02,Laptop,2,55000,110000,Cash,4.5
190,SP100190,Dev Mehta,Male,28.0,Pune,2025-02-28,Mouse,3,600,1800,UPI,5.0
195,SP100195,Priya Singh,Female,36.0,Bengaluru,2025-07-14,Charger,4,900,3600,Cash,2.0