In [1]:
import pandas as pd
df=pd.read_csv('orders_practice.csv')
df.columns

Index(['Order ID', 'Customer Name', 'Gender', 'Age', 'City', 'Order Date',
       'Product', 'Qty', 'Unit Price', 'Total Amount', 'Payment Mode',
       'Rating'],
      dtype='str')

In [16]:
big_orders=df['Total Amount']>50000
df[big_orders]
len(df[big_orders])

40

In [22]:
pune_city=(df['City']=='Pune')
len(df[pune_city])

25

In [35]:
mumbai_orders=(df['City']=='Mumbai')
not_mumbai_id=df.loc[~mumbai_orders,'Order ID']
print(not_mumbai_id)

1      SP100001
2      SP100002
3      SP100003
4      SP100004
5      SP100005
         ...
195    SP100195
196    SP100196
197    SP100197
198    SP100198
199    SP100199
Name: Order ID, Length: 162, dtype: str

In [44]:
qty_mode=(df['Qty']>=4)&(df['Payment Mode']=='UPI')
df[qty_mode]

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
0,SP100000,Isha Singh,Male,58.0,Mumbai,2025-09-12,Laptop,4,55000,220000,UPI,1.0
6,SP100006,Meera Iyer,Male,32.0,Nashik,2025-05-16,Charger,4,900,3600,UPI,3.5
11,SP100011,Pooja Singh,Female,NaN,Mumbai,2025-02-21,Headphones,4,2500,10000,UPI,1.0
36,SP100036,Vikram Gupta,Male,41.0,Delhi,2025-04-26,Webcam,5,2200,11000,UPI,4.5
42,SP100042,Riya Verma,Male,25.0,Nashik,2025-10-21,Charger,4,900,3600,UPI,4.5
43,SP100043,Sahil Patil,Male,22.0,Bengaluru,2025-12-05,Laptop,4,55000,220000,UPI,3.0
65,SP100065,Vikram Gupta,Female,42.0,Chennai,2025-08-20,Keyboard,4,1200,4800,UPI,3.0
69,SP100069,Yash Iyer,Male,28.0,Chennai,2025-08-04,Charger,4,900,3600,UPI,1.0
88,SP100088,Arjun Patil,Female,-5.0,Mumbai,2025-03-12,Laptop,5,55000,275000,UPI,2.0
89,SP100089,Rahul Iyer,Female,46.0,Bengaluru,2025-01-20,Laptop,4,55000,220000,UPI,4.0
98,SP100098,Rahul Joshi,Female,48.0,Bengaluru,2025-04-26,Mouse,4,600,2400,UPI,4.5
101,SP100101,Vikram Nair,Female,57.0,Delhi,2025-06-30,Headphones,4,2500,10000,UPI,1.0
128,SP100128,Meera Gupta,Male,18.0,Nashik,2025-03-27,Monitor,4,9000,36000,UPI,4.0
147,SP100147,Arjun Mehta,Female,31.0,Delhi,2025-05-24,Charger,4,900,3600,UPI,3.0
152,SP100152,Sneha Patil,Female,18.0,Pune,2025-02-20,Webcam,4,2200,8800,UPI,5.0
160,SP100160,Sahil Nair,Male,60.0,Mumbai,2025-08-05,Headphones,4,2500,10000,UPI,1.0
163,SP100163,Priya Gupta,Male,42.0,Mumbai,2025-08-15,Mouse,5,600,3000,UPI,2.0
173,SP100173,Isha Gupta,Female,55.0,Bengaluru,2025-02-06,Webcam,5,2200,11000,UPI,2.0
181,SP100181,Isha Singh,Female,21.0,Pune,2025-04-03,Phone,4,22000,88000,UPI,3.0
183,SP100183,Pooja Shah,Male,22.0,Nashik,2025-04-22,Headphones,5,2500,12500,UPI,3.5
197,SP100197,Isha Nair,Female,18.0,Nashik,2025-05-05,Webcam,5,2200,11000,UPI,4.5
198,SP100198,Priya Kulkarni,Female,55.0,Chennai,2025-03-19,Monitor,4,9000,36000,UPI,5.0

In [46]:
laptop_phone=(df.iloc[:,6]=='Laptop')|(df.iloc[:,6]=='Phone')
df[laptop_phone]

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
0,SP100000,Isha Singh,Male,58.0,Mumbai,2025-09-12,Laptop,4,55000,220000,UPI,1.0
4,SP100004,Dev Nair,Male,64.0,Delhi,2025-11-22,Phone,4,22000,88000,Cash,4.5
17,SP100017,Riya Kulkarni,Female,39.0,Chennai,2025-02-28,Laptop,1,55000,55000,Net Banking,3.5
22,SP100022,Dev Mehta,Female,31.0,Chennai,2025-07-31,Phone,3,22000,66000,Cash,2.0
24,SP100024,Priya Joshi,Female,20.0,Chennai,2025-06-01,Phone,3,22000,66000,Net Banking,1.0
25,SP100025,Sneha Nair,Female,NaN,Chennai,2025-02-07,Phone,3,22000,66000,UPI,4.0
38,SP100038,Yash Mehta,Male,22.0,Mumbai,2025-10-31,Laptop,5,55000,275000,Net Banking,2.0
41,SP100041,Anjali Patil,Male,49.0,Nashik,2025-02-14,Phone,2,22000,44000,Card,3.5
43,SP100043,Sahil Patil,Male,22.0,Bengaluru,2025-12-05,Laptop,4,55000,220000,UPI,3.0
50,SP100050,Kavya Gupta,Male,38.0,Bengaluru,2025-04-01,Laptop,4,55000,220000,Card,2.0
58,SP100058,Rohan Shah,Male,62.0,Chennai,2025-02-06,Laptop,5,55000,275000,Net Banking,4.5
66,SP100066,Aarav Mehta,Female,50.0,Bengaluru,2025-11-11,Phone,4,22000,88000,Net Banking,1.0
72,SP100072,Sahil Patil,Female,21.0,Chennai,2025-02-02,Phone,5,22000,110000,Card,4.0
76,SP100076,Yash Iyer,Male,NaN,Bengaluru,2025-06-24,Phone,3,22000,66000,UPI,3.0
79,SP100079,Dev Gupta,Male,30.0,Nashik,2025-06-17,Laptop,3,55000,165000,Card,3.5
80,SP100080,Rahul Iyer,Female,55.0,Bengaluru,2025-02-10,Laptop,2,55000,110000,Card,5.0
81,SP100081,Isha Mehta,Female,57.0,Mumbai,2025-02-08,Laptop,5,55000,275000,Cash,5.0
82,SP100082,Rohan Joshi,Female,20.0,Chennai,2025-11-24,Laptop,4,55000,220000,Net Banking,1.0
83,SP100083,Neha Patil,Female,54.0,Chennai,2025-03-14,Phone,2,22000,44000,UPI,5.0
88,SP100088,Arjun Patil,Female,-5.0,Mumbai,2025-03-12,Laptop,5,55000,275000,UPI,2.0
89,SP100089,Rahul Iyer,Female,46.0,Bengaluru,2025-01-20,Laptop,4,55000,220000,UPI,4.0
90,SP100090,Vikram Gupta,Male,51.0,NaN,2025-03-05,Laptop,1,55000,55000,Card,1.0
95,SP100095,Karan Singh,Female,46.0,Delhi,2025-08-20,Laptop,2,55000,110000,Net Banking,3.0
96,SP100096,Sahil Mehta,Female,45.0,Bengaluru,2025-04-26,Phone,3,22000,66000,Net Banking,1.0
102,SP100102,Tanvi Gupta,Female,18.0,Mumbai,2025-04-13,Laptop,1,55000,55000,Cash,3.0
112,SP100112,Anjali Mehta,Female,58.0,Nashik,2025-08-21,Laptop,1,55000,55000,Cash,4.0
125,SP100125,Priya Kulkarni,Female,20.0,Pune,2025-07-22,Phone,3,22000,66000,Cash,4.5
129,SP100129,Arjun Shah,Female,41.0,Pune,2025-09-05,Phone,5,22000,110000,Cash,1.0
132,SP100132,Rahul Gupta,Female,25.0,Chennai,2025-01-31,Laptop,2,55000,110000,Cash,3.0
135,SP100135,Neha Iyer,Male,40.0,Delhi,2025-02-19,Laptop,2,55000,110000,UPI,3.0
136,SP100136,Meera Mehta,Female,16.0,Pune,2025-06-15,Laptop,1,55000,55000,Net Banking,4.0
141,SP100141,Anjali Kulkarni,Female,55.0,Bengaluru,2025-06-10,Laptop,3,55000,165000,Net Banking,3.5
148,SP100148,Anjali Patil,Male,59.0,Mumbai,2025-01-01,Phone,1,22000,22000,UPI,3.5
153,SP100153,Yash Patil,Female,17.0,Mumbai,2025-02-10,Laptop,1,55000,55000,Cash,4.0
157,SP100157,Dev Gupta,Male,31.0,Bengaluru,2025-10-19,Laptop,2,55000,110000,UPI,4.0
165,SP100165,Priya Verma,Male,27.0,Nashik,2025-11-15,Phone,1,22000,22000,Net Banking,2.0
172,SP100172,Isha Kulkarni,Female,55.0,Nashik,2025-07-28,Laptop,4,55000,220000,Card,1.0
178,SP100178,Aarav Iyer,Female,28.0,Pune,2025-02-06,Laptop,2,55000,110000,Card,4.5
180,SP100180,Neha Mehta,Male,18.0,Mumbai,2025-06-25,Laptop,3,55000,165000,UPI,5.0
181,SP100181,Isha Singh,Female,21.0,Pune,2025-04-03,Phone,4,22000,88000,UPI,3.0
185,SP100185,Neha Patil,Male,58.0,Delhi,2025-08-02,Laptop,2,55000,110000,Cash,4.5
187,SP100187,Karan Iyer,Male,22.0,Pune,2025-11-24,Laptop,2,55000,110000,Cash,NaN
189,SP100189,Tanvi Kulkarni,Male,58.0,Bengaluru,2025-11-16,Phone,2,22000,44000,Cash,3.0
191,SP100191,Aarav Kulkarni,Male,41.0,Pune,2025-06-29,Laptop,5,55000,275000,Card,NaN
193,SP100193,Sahil Iyer,Male,24.0,Delhi,2025-07-22,Laptop,3,55000,165000,Net Banking,2.0
194,SP100194,Tanvi Shah,Male,21.0,Mumbai,2025-12-01,Phone,2,22000,44000,UPI,3.0

In [49]:
webcam_monitor=df['Product'].isin(['Webcam','Monitor'])
df[webcam_monitor]

,Order ID,Customer Name,Gender,Age,City,Order Date,Product,Qty,Unit Price,Total Amount,Payment Mode,Rating
5,SP100005,Meera Singh,Male,18.0,Bengaluru,2025-02-26,Webcam,1,2200,2200,Cash,4.0
7,SP100007,Neha Patil,Female,150.0,Pune,2025-03-24,Webcam,1,2200,2200,Cash,4.0
10,SP100010,Sahil Shah,Female,55.0,Chennai,2025-08-31,Webcam,1,2200,2200,Card,4.0
15,SP100015,Yash Mehta,Male,49.0,Mumbai,2025-07-23,Webcam,2,2200,4400,Cash,4.5
19,SP100019,Karan Nair,Female,20.0,Delhi,2025-02-13,Monitor,4,9000,36000,Card,5.0
26,SP100026,Anjali Iyer,Female,45.0,Delhi,2025-05-07,Webcam,1,2200,2200,Cash,4.0
29,SP100029,Kavya Nair,Female,42.0,Nashik,2025-06-10,Webcam,2,2200,4400,Card,1.0
31,SP100031,Rohan Mehta,Male,48.0,Chennai,2025-09-23,Monitor,4,9000,36000,Net Banking,4.5
34,SP100034,Karan Verma,Female,28.0,Nashik,2025-12-08,Monitor,2,9000,18000,UPI,2.0
36,SP100036,Vikram Gupta,Male,41.0,Delhi,2025-04-26,Webcam,5,2200,11000,UPI,4.5
39,SP100039,Meera Verma,Female,59.0,Mumbai,2025-03-13,Monitor,1,9000,9000,Card,3.0
46,SP100046,Dev Singh,Male,64.0,Mumbai,2025-08-06,Monitor,1,9000,9000,UPI,5.0
47,SP100047,Arjun Singh,Female,55.0,Nashik,2025-01-07,Monitor,5,9000,45000,Cash,1.0
54,SP100054,Sneha Patil,Female,18.0,NaN,2025-08-04,Monitor,1,9000,9000,Cash,4.0
55,SP100055,Sahil Nair,Female,41.0,Chennai,2025-11-16,Webcam,2,2200,4400,Net Banking,4.5
59,SP100059,Vikram Iyer,Male,56.0,Bengaluru,2025-10-12,Webcam,5,2200,11000,Cash,4.0
61,SP100061,Riya Nair,Female,47.0,Pune,2025-04-08,Webcam,3,2200,6600,UPI,1.0
63,SP100063,Arjun Nair,Male,50.0,Pune,2025-04-19,Monitor,2,9000,18000,Net Banking,5.0
64,SP100064,Tanvi Singh,Female,32.0,Delhi,2025-07-15,Monitor,5,9000,45000,Net Banking,4.5
68,SP100068,Kavya Iyer,Male,56.0,Delhi,2025-08-05,Monitor,1,9000,9000,Card,NaN
71,SP100071,Dev Kulkarni,Female,55.0,Bengaluru,2025-06-29,Monitor,3,9000,27000,UPI,4.0
73,SP100073,Yash Kulkarni,Male,49.0,Chennai,2025-05-02,Monitor,3,9000,27000,Cash,5.0
74,SP100074,Karan Mehta,Female,34.0,Bengaluru,2025-04-25,Webcam,4,2200,8800,Card,2.0
77,SP100077,Aarav Kulkarni,Female,63.0,Delhi,2025-02-13,Monitor,5,9000,45000,Card,4.5
91,SP100091,Meera Iyer,Female,38.0,Bengaluru,2025-10-14,Webcam,1,2200,2200,Card,4.0
92,SP100092,Arjun Patil,Male,63.0,Bengaluru,2025-04-20,Webcam,3,2200,6600,Card,NaN
94,SP100094,Yash Singh,Male,21.0,Nashik,2025-02-18,Monitor,3,9000,27000,Net Banking,2.0
100,SP100100,Pooja Gupta,Male,62.0,Nashik,2025-07-03,Webcam,4,2200,8800,Cash,3.5
104,SP100104,Arjun Nair,Female,23.0,Pune,2025-08-08,Monitor,5,9000,45000,Cash,NaN
106,SP100106,Rohan Kulkarni,Female,35.0,NaN,2025-08-22,Webcam,4,2200,8800,Card,1.0
107,SP100107,Riya Verma,Male,24.0,Chennai,2025-03-02,Monitor,2,9000,18000,Card,4.5
111,SP100111,Sneha Mehta,Male,40.0,Nashik,2025-08-03,Monitor,2,9000,18000,Cash,NaN
117,SP100117,Meera Patil,Male,32.0,Pune,2025-03-11,Monitor,4,9000,36000,Card,1.0
122,SP100122,Kavya Joshi,Male,64.0,Mumbai,2025-12-26,Monitor,3,9000,27000,UPI,3.0
123,SP100123,Kavya Kulkarni,Female,33.0,Mumbai,2025-02-15,Webcam,4,2200,8800,Card,1.0
128,SP100128,Meera Gupta,Male,18.0,Nashik,2025-03-27,Monitor,4,9000,36000,UPI,4.0
130,SP100130,Isha Gupta,Female,49.0,Pune,2025-03-28,Webcam,3,2200,6600,Card,4.5
140,SP100140,Anjali Nair,Male,23.0,Delhi,2025-11-16,Webcam,2,2200,4400,UPI,2.0
144,SP100144,Yash Singh,Male,17.0,Nashik,2025-12-17,Webcam,3,2200,6600,Cash,1.0
146,SP100146,Aarav Shah,Female,21.0,NaN,2025-05-21,Webcam,2,2200,4400,Net Banking,1.0
152,SP100152,Sneha Patil,Female,18.0,Pune,2025-02-20,Webcam,4,2200,8800,UPI,5.0
159,SP100159,Meera Shah,Female,24.0,Bengaluru,2025-09-22,Monitor,2,9000,18000,Net Banking,4.0
161,SP100161,Isha Joshi,Male,24.0,Chennai,2025-07-05,Webcam,1,2200,2200,UPI,5.0
164,SP100164,Arjun Verma,Male,30.0,Delhi,2025-08-31,Monitor,1,9000,9000,Net Banking,4.5
167,SP100167,Anjali Kulkarni,Female,NaN,Mumbai,2025-06-03,Webcam,3,2200,6600,Net Banking,3.5
169,SP100169,Isha Nair,Male,50.0,Delhi,2025-02-24,Webcam,5,2200,11000,Card,5.0
173,SP100173,Isha Gupta,Female,55.0,Bengaluru,2025-02-06,Webcam,5,2200,11000,UPI,2.0
186,SP100186,Sahil Nair,Female,36.0,Mumbai,2025-10-05,Monitor,2,9000,18000,UPI,4.5
196,SP100196,Rohan Gupta,Female,53.0,NaN,2025-06-21,Webcam,5,2200,11000,Net Banking,2.0
197,SP100197,Isha Nair,Female,18.0,Nashik,2025-05-05,Webcam,5,2200,11000,UPI,4.5
198,SP100198,Priya Kulkarni,Female,55.0,Chennai,2025-03-19,Monitor,4,9000,36000,UPI,5.0

In [51]:
women_delhi=(df['Gender']=='Female')&(df['City']=='Delhi')
df.loc[women_delhi,['Customer Name','Product','Rating']]

      Customer Name     Product  Rating
2        Sneha Iyer       Mouse     3.5
19       Karan Nair     Monitor     5.0
26      Anjali Iyer      Webcam     4.0
53      Sneha Mehta       Mouse     1.0
62      Sneha Singh    Keyboard     3.0
64      Tanvi Singh     Monitor     4.5
77   Aarav Kulkarni     Monitor     4.5
95      Karan Singh      Laptop     3.0
101     Vikram Nair  Headphones     1.0
147     Arjun Mehta     Charger     3.0
175      Karan Nair     Charger     4.0
184     Sahil Gupta    Keyboard     2.0